export const useFilterState = () =>
  useState("filter", () => ({
    search: "",
    colors: {
      white: false,
      green: false,
      red: false,
      blue: false,
      purple: false,
      yellow: false,
      blue_red: false,
    },
    cardTypes: {
      buzzCharacter: false,
      character: false,
      oshiCharacter: false,
      supportCheer: false,
      supportEvent: false,
      supportEventLimited: false,
      supportFan: false,
      supportItem: false,
      supportLocation: false,
      supportTool: false,
    },
    rarity: {
      C: false,
      OC: false,
      OSR: false,
      OUR: false,
      P: false,
      R: false,
      RR: false,
      S: false,
      SEC: false,
      SR: false,
      SY: false,
      U: false,
      UR: false,
    },
    bloomLevel: {
      debut: false,
      "1st": false,
      "2nd": false,
      spot: false,
    },
  }));
